# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration
   ### As its specified in setting.py file we have ENV as a default so we can specify them in docekr compose for reusability
ENV ENGINE=""
ENV NAME=""
ENV USER=""
ENV PASSWORD=""
ENV HOST=""
ENV PORT=""

# Expose port 3306 for MySQL connections
EXPOSE 3306

# Set the data directory as a volume
VOLUME /var/lib/mysql
